name: Jobcan Last Month Execution

env:
  #スプレッドシート認証情報
  AUTH_GOOGLE_EMAIL: ${{ secrets.AUTH_GOOGLE_EMAIL }}
  AUTH_GOOGLE_KEY: ${{ secrets.AUTH_GOOGLE_KEY }}
  AUTH_GOOGLE_SHEET_ID: ${{ secrets.AUTH_GOOGLE_SHEET_ID }}
  # ジョブカン情報
  JOBCAN_AUTH_COMPANY: ${{ secrets.JOBCAN_AUTH_COMPANY }}
  JOBCAN_AUTH_EMAIL: ${{ secrets.JOBCAN_AUTH_EMAIL }}
  JOBCAN_AUTH_PASSWORD: ${{ secrets.JOBCAN_AUTH_PASSWORD }}

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 1 * *"
    - cron: "0 10 2 * *"

jobs:
  Run-Batch-Process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.18

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Set current month as env
        run: |
          CURRENT_YYYYMM=$(date +%Y%m)
          echo "CURRENT_YYYYMM=$CURRENT_YYYYMM" >> $GITHUB_ENV

      - name: run batch process with current month arg
        run: bun index.ts $CURRENT_YYYYMM
