name: Jobcan Current Month Execution

env:
  #スプレッドシート認証情報
  AUTH_GOOGLE_EMAIL: ${{ secrets.AUTH_GOOGLE_EMAIL }}
  AUTH_GOOGLE_KEY: ${{ secrets.AUTH_GOOGLE_KEY }}
  AUTH_GOOGLE_SHEET_ID: ${{ secrets.AUTH_GOOGLE_SHEET_ID }}
  # ジョブカン情報
  JOBCAN_AUTH_COMPANY: ${{ secrets.JOBCAN_AUTH_COMPANY }}
  JOBCAN_AUTH_EMAIL: ${{ secrets.JOBCAN_AUTH_EMAIL }}
  JOBCAN_AUTH_PASSWORD: ${{ secrets.JOBCAN_AUTH_PASSWORD }}

on:
  workflow_dispatch:
  schedule:
    # 毎日午前5時（JST）に実行
    - cron: "0 20 * * *"

jobs:
  Run-Batch-Process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.18

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Set current month as env
        run: |
          CURRENT_DATE=$(date +%Y-%m-15)
          YYYYMM=$(date --date="$CURRENT_DATE month" +%Y%m)
          echo "YYYYMM=$YYYYMM" >> $GITHUB_ENV

      - name: run batch process with last month arg
        run: bun index.ts $YYYYMM
