name: Jobcan Scheduled Execution

env:
  #スプレッドシート認証情報
  AUTH_GOOGLE_EMAIL: ${{ secrets.AUTH_GOOGLE_EMAIL }}
  # ジョブカン情報
  JOBCAN_URL: ${{ secrets.JOBCAN_URL }}
  JOBCAN_AUTH_COMPANY: ${{ secrets.JOBCAN_AUTH_COMPANY }}
  JOBCAN_AUTH_EMAIL: ${{ secrets.JOBCAN_AUTH_EMAIL }}
  JOBCAN_AUTH_PASSWORD: ${{ secrets.JOBCAN_AUTH_PASSWORD }}

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  Run-Batch-Process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.18

      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Decode Firebase service account key
        run: |
          echo "${{ secrets.ENCRYPTED_AUTH_GOOGLE_KEY }}" | base64 -d > ./google-key.json
          echo "AUTH_GOOGLE_KEY=${{ github.workspace }}/google-key.json" >> $GITHUB_ENV

      - name: run batch process
        run: bun index.ts
